name: Test, Lint, and Build

on: pull_request

jobs:
  test-unit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install Dependencies
      run: |
        npm i
    - name: Run Unit Tests
      run: |
        CI=true npm run test:all-unit

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install Dependencies
        run: |
          npm i
      - name: Run Lint
        run: |
          npm run lint
      - name: Run Format Check
        run: |
          npm run format:check

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install Dependencies
        run: |
          npm i
      - name: Run Build
        run: |
          npm run build
